jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/demo?userUnicode=true&characterEncoding=utf8&useSSL=false
  username: root
  password: 520520
sessionfactory:
  mybatis_config_filepath: mybatis-config.xml
  mapper_path: /mapper/**.xml
  entity_package: com.westf.mybatisdemo.entity

